routes/web.php
<?php

use App\Http\Controllers\FormController;
use App\Http\Controllers\MsgController;
use App\Http\Controllers\PortafolioController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::view('/home', 'home')->name('home'); // Inicio
Route::view('/about', 'about')->name('about'); // Sobre mi
Route::get('/portafolio', PortafolioController::class)->name('portafolio'); // Portafolio
Route::view('/contact', 'contact')->name('contact'); // Contacto
Route::post('/contact', [MsgController::class, 'store']);
Route::view('/description', 'description')->name('description'); // Descripción
// Route::get('/ejercicio', 'ProyectoController')->name('ejercicio'); // Ejercicio de prueba

Route::resource('/form', FormController::class)->only(['index', 'store']);

app/Helpers.php
<?php

/**
 * Devuelve active en caso el nombre de la ruta sea la enviada para activar la clase
 */
function isRouteActiveName($routeName)
{
  return request()->routeIs($routeName) ? 'active' : '';
};

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FormController extends Controller
{
    public function index()
    {
        return view('midterm-exam.index');
    }

    public function store(Request $request)
    {
        $request->validate([
            'full_name' => 'required',
            'email' => 'required|email',
            'cell_phone' => 'required|numeric|min:9',
            'address' => 'required|numeric|min:9'
        ],
        [
            'full_name.required' => 'Necesitamos tu nombre completo para dirigirnos contigo',
            'email.required' => 'Necesitamos tu correo para poder contactarte',
            'cell_phone.required' => 'Agrega tu celular para poder comunicarnos contigo'
        ]);

        return view('midterm-exam.index', compact($request));
    }

}

app/Http/Controllers/MsgController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MsgController extends Controller
{
    public function store(Request $request)
    {
        $request->validate([
            'full_name' => 'required',
            'email' => 'required|email',
            'subject' => 'required',
            'content' => 'required|min:3'
        ],
        [
            'full_name.required' => 'Necesitamos tu nombre completo para dirigirnos contigo',
            'email.required' => 'Necesitamos tu correo para poder contactarte'
        ]);

        return "Datos validados";
    }
}

app/Http/Controllers/PortafolioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PortafolioController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $portafolios = [
            ['title' => 'Proyecto #1'],
            ['title' => 'Proyecto #2'],
            ['title' => 'Proyecto #3'],
            ['title' => 'Proyecto #4'],
        ];

        return view('portafolio', compact('portafolios'));
    }
}

app/Http/Controllers/TestController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/about.blade.php
@extends('./theme/layout')

@section('title', ' - About')

@section('content')
  <h1>About</h1>
@endsection

resources/views/contact.blade.php
@extends('./theme/layout')

@section('title', ' - Contact')

@section('content')
  <h1>{{ __('Contact')}}</h1>

  <form class="row" method="POST" action="{{ route('contact') }}">
    @csrf
    <div class="mb-3">
      <label for="full_name" class="col-form-label">Nombre completo</label>
      <input type="text" class="form-control @error('full_name') is-invalid @enderror" id="full_name" name="full_name"
        placeholder="Pablito Calvo" value="{{ old('full_name') }}">
      @error('full_name')
        <div class="invalid-feedback">{{ $message }}</div>
      @enderror
    </div>
    <div class="mb-3">
      <label for="email" class="col-form-label">Email</label>
      <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email"
        placeholder="example@gmail.com" value="{{ old('email') }}">
      @error('email')
        <div class="invalid-feedback">{{ $message }}</div>
      @enderror
    </div>
    <div class="mb-3">
      <label for="subject" class="col-form-label">Asunto</label>
      <input type="text" class="form-control @error('subject') is-invalid @enderror" id="subject" name="subject"
        placeholder="..." value="{{ old('subject') }}">
      @error('subject')
        <div class="invalid-feedback">{{ $message }}</div>
      @enderror
    </div>
    <div class="mb-3">
      <label for="content" class="col-form-label">Mensaje</label><br>
      <textarea class="form-control @error('content') is-invalid @enderror" name="content" id="content" rows="5">{{ old('content') }}</textarea>
      @error('content')
        <div class="invalid-feedback">{{ $message }}</div>
      @enderror
    </div>

    <div class="col-auto">
      <button type="submit" class="btn btn-primary mb-3">Enviar</button>
    </div>
  </form>
@endsection

resources/views/description.blade.php
@extends('./theme/layout')

@section('title', ' - Description')

@section('content')
  <h1>Description</h1>
@endsection

resources/views/home.blade.php
@extends('./theme/layout')

@section('title', ' - Home')

@section('content')
  <h1>Home</h1>
@endsection

resources/views/midterm-exam/index.blade.php
@extends('./theme/layout')

@section('title', ' - Examen parcial')

@section('content')
  <h1>Agregar contacto</h1>

  <form class="row" method="POST" action="{{ route('form.store') }}">
    @csrf
    <div class="mb-3">
      <label for="full_name" class="col-form-label">Nombre completo</label>
      <input type="text" class="form-control @error('full_name') is-invalid @enderror" id="full_name" name="full_name"
        placeholder="Pablito Calvo" value="{{ old('full_name') }}">
      @error('full_name')
        <div class="invalid-feedback">{{ $message }}</div>
      @enderror
    </div>
    <div class="mb-3">
      <label for="email" class="col-form-label">Email</label>
      <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email"
        placeholder="ejemplo@gmail.com" value="{{ old('email') }}">
      @error('email')
        <div class="invalid-feedback">{{ $message }}</div>
      @enderror
    </div>
    <div class="mb-3">
      <label for="cell_phone" class="col-form-label">Celular</label>
      <input type="text" class="form-control @error('cell_phone') is-invalid @enderror" id="cell_phone" name="cell_phone"
        placeholder="954862358" value="{{ old('cell_phone') }}">
      @error('cell_phone')
        <div class="invalid-feedback">{{ $message }}</div>
      @enderror
    </div>
    <div class="mb-3">
      <label for="address" class="col-form-label">Dirección</label>
      <input type="text" class="form-control @error('address') is-invalid @enderror" id="address" name="address"
        placeholder="Av. Ejemplo 245 - Huancayo" value="{{ old('address') }}">
      @error('address')
        <div class="invalid-feedback">{{ $message }}</div>
      @enderror
    </div>

    <div class="col-auto">
      <button type="submit" class="btn btn-primary mb-3">Guardar</button>
    </div>
  </form>
@endsection

resources/views/portafolio.blade.php
@extends('./theme/layout')

@section('title', ' - Portafolio')

@section('content')

<h1>Portafolio</h1>

<ul>
  @forelse ( $portafolios as $portafolio)
    <li>{{ $portafolio['title'] }}</li>
  @empty
    <li>No hay proyectos para mostrar.</li>
  @endforelse
</ul>

@endsection

resources/views/theme/footer.blade.php
{{-- <!-- Pié de página -->
<footer class="footer">
  <div class="container-fluid">
    <div class="row text-muted">
      <div class="col-6 text-start">
        <p class="mb-0">
          <a class="text-muted" href="https://adminkit.io/" target="_blank"><strong>AdminKit</strong></a> - <a class="text-muted" href="https://adminkit.io/" target="_blank"><strong>Bootstrap Admin Template</strong></a>								&copy;
        </p>
      </div>
      <div class="col-6 text-end">
        <ul class="list-inline">
          <li class="list-inline-item">
            <a class="text-muted" href="https://adminkit.io/" target="_blank">Support</a>
          </li>
          <li class="list-inline-item">
            <a class="text-muted" href="https://adminkit.io/" target="_blank">Help Center</a>
          </li>
          <li class="list-inline-item">
            <a class="text-muted" href="https://adminkit.io/" target="_blank">Privacy</a>
          </li>
          <li class="list-inline-item">
            <a class="text-muted" href="https://adminkit.io/" target="_blank">Terms</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer> --}}

resources/views/theme/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>juliopalro @yield('title')</title>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  </head>

  <body>
    <div class="wrapper">
      @include('theme.sidebar')

      <div class="main">
        @include('theme.navbar')

        <!-- Cuerpo de la página-->
        <main class="content">
          <div class="container-fluid p-0">
            @yield('content')
          </div>
        </main>

        @include('theme.footer')
      </div>
    </div>

    <!-- Script -->
    <script src="{{ asset('js/app.js') }}" defer></script>
  </body>
</html>

resources/views/theme/navbar.blade.php
<!-- Menú top -->
<nav class="navbar navbar-expand navbar-light navbar-bg">
  <a class="sidebar-toggle js-sidebar-toggle">
    <i class="hamburger align-self-center"></i>
  </a>

  <div class="navbar-collapse collapse">
    <ul class="navbar-nav navbar-align">
      <!-- Profile -->
      <li class="nav-item dropdown">
        <a class="nav-icon pe-md-0 dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
          <div class="avatar img-fluid rounded me-1" alt="Charles Hall">
            <i class="align-middle" data-feather="user"></i>
          </div>
        </a>

        <div class="dropdown-menu dropdown-menu-end">
          <a class="dropdown-item" href="pages-profile.html"><i class="align-middle me-1" data-feather="user"></i> Profile</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Log out</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

resources/views/theme/sidebar.blade.php
<!-- menú left -->
<nav id="sidebar" class="sidebar js-sidebar">
  <div class="sidebar-content js-simplebar">
    <a class="sidebar-brand" href="{{ route('home') }}">
      <span class="align-middle">Juliopalro</span>
    </a>

    <ul class="sidebar-nav">
      <li class="sidebar-header">Páginas</li>
      <li class="sidebar-item {{ isRouteActiveName('home') }}">
        <a class="sidebar-link" href="{{ route('home') }}">
          <i class="align-middle" data-feather="home"></i> <span class="align-middle">{{ __('Home')}}</span>
        </a>
      </li>
      <li class="sidebar-item {{ isRouteActiveName('about') }}">
        <a class="sidebar-link" href="{{ route('about') }}">
          <i class="align-middle" data-feather="user"></i> <span class="align-middle">{{ __('About')}}</span>
        </a>
      </li>
      <li class="sidebar-item {{ isRouteActiveName('portafolio') }}">
        <a class="sidebar-link" href="{{ route('portafolio') }}">
          <i class="align-middle" data-feather="folder"></i> <span class="align-middle">{{ __('Portfolio')}}</span>
        </a>
      </li>
      <li class="sidebar-item {{ isRouteActiveName('contact') }}">
        <a class="sidebar-link" href="{{ route('contact') }}">
          <i class="align-middle" data-feather="edit"></i> <span class="align-middle">{{ __('Contact')}}</span>
        </a>
      </li>
      <li class="sidebar-item {{ isRouteActiveName('description') }}">
        <a class="sidebar-link" href="{{ route('description') }}">
          <i class="align-middle" data-feather="align-center"></i> <span class="align-middle">{{ __('Description')}}</span>
        </a>
      </li>
      <li class="sidebar-item {{ isRouteActiveName('form.index') }}">
        <a class="sidebar-link" href="{{ route('form.index') }}">
          <i class="align-middle" data-feather="align-center"></i> <span class="align-middle">Examen parcial</span>
        </a>
      </li>
    </ul>
  </div>
</nav>